alias: 'Switch off light in main room at 11:30pm'
initial_state: 'on'
trigger:
  - platform: time
    at: '23:30:00'
action:
  - service: switch.turn_off
    entity_id: switch.light1
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.switch_light1
