alias: 'Switch off light in main room when Stas is away after sunset'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.stas_at_home
    to: 'off'
action:
  - service: switch.turn_off
    entity_id: switch.light1
