alias: 'Switch on light in main room when Stas or Sveta at home after sunset'
initial_state: 'on'
trigger:
  - platform: sun
    event: sunset
    offset: '-00:30:00'
  - platform: homeassistant
    event: start
condition:
  condition: or
  conditions:
    - condition: state
      entity_id: input_boolean_stas_at_home
      state: home
    - condition: state
      entity_id: input_boolean_sveta_at_home
      state: home
action:
  - service: switch.turn_on
    entity_id: switch.light1
