alias: 'Switch on light in main room when Stas at home after sunset'
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.stas_at_home
    to: 'on'
condition:
  condition: or
  conditions:
    - condition: sun
      after: sunset
    - condition: sun
      before: sunrise
action:
  - service: switch.turn_on
    entity_id: switch.light1
