alias: armed_alarm
initial_state: 'on'
trigger:
  - platform: state
    entity_id: input_boolean.stas_at_home
    to: 'off'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.alarm_armed
    state: 'off'
action:
  - service: shell_command.start_motion
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.alarm_armed
#  - service: notify.telegram_notif
#    data:
#      message: "Alarm armed"
