alias: telegram_sveta_is_away
initial_state: 'on'
trigger:
  - platform: state
    entity_id:
    - device_tracker.sveta_phone_wifi
    - device_tracker.sveta_phone_bt
    to: 'not_home'
  - platform: homeassistant
    event: start
condition:
  - condition: state
    entity_id: input_boolean.sveta_at_home
    state: 'on'
  - condition: state
    entity_id: device_tracker.sveta_phone_wifi
    state: 'not_home'
  - condition: state
    entity_id: device_tracker.sveta_phone_bt
    state: 'not_home'
action:
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.sveta_at_home
#  - service: notify.telegram_notif
#    data:
#      message: "Sveta is away"
